/*
	SDZSkuServiceExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "SDZSkuServiceExample.h"
#import "SDZSkuService.h"

@implementation SDZSkuServiceExample

- (void)run {
	// Create the service
	SDZSkuService* service = [SDZSkuService service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

	// Returns NSString*. 
	[service getSkuDetails:self action:@selector(getSkuDetailsHandler:) skuID: @""];

	// Returns NSString*. 
	[service getSkuID:self action:@selector(getSkuIDHandler:)];

	// Returns NSString*. 
	[service getSkuIDForGivenProductName:self action:@selector(getSkuIDForGivenProductNameHandler:) productName: @""];

	// Returns NSString*. 
	[service searchProduct:self action:@selector(searchProductHandler:) searchCriteria: @""];
}

	

// Handle the response from getSkuDetails.
		
- (void) getSkuDetailsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		//NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		//NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
	//NSLog(@"getSkuDetails returned the value: %@", result);
			
}
	

// Handle the response from getSkuID.
		
- (void) getSkuIDHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		//NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		//NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
	//NSLog(@"getSkuID returned the value: %@", result);
			
}
	

// Handle the response from getSkuIDForGivenProductName.
		
- (void) getSkuIDForGivenProductNameHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		//NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		//NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
	//NSLog(@"getSkuIDForGivenProductName returned the value: %@", result);
			
}
	

// Handle the response from searchProduct.
		
- (void) searchProductHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		//NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		//NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
	//NSLog(@"searchProduct returned the value: %@", result);
			
}
	

@end
		