/*
	SDZLoyaltycardServiceExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "SDZLoyaltycardServiceExample.h"
#import "SDZLoyaltycardService.h"

@implementation SDZLoyaltycardServiceExample

- (void)run {
	// Create the service
	SDZLoyaltycardService* service = [SDZLoyaltycardService service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

	// Returns NSString*. 
	[service getLoyalcardDetails:self action:@selector(getLoyalcardDetailsHandler:) loyaltyCardNumber: @""];

	// Returns NSString*. 
	[service getissuedLoyaltycard:self action:@selector(getissuedLoyaltycardHandler:) loyaltyCardNumber: @""];

	// Returns NSString*. 
	[service getloyaltyCardNumber:self action:@selector(getloyaltyCardNumberHandler:)];

	// Returns NSString*. 
	[service supplyLoyaltyCard:self action:@selector(supplyLoyaltyCardHandler:) customerName: @"" phone: @"" email: @"" idType: @"" idCardNumber: @"" loyaltyProgramNumber: @"" loyaltyCardNumber: @""];
}

	

// Handle the response from getLoyalcardDetails.
		
- (void) getLoyalcardDetailsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
	//NSLog(@"getLoyalcardDetails returned the value: %@", result);
			
}
	

// Handle the response from getissuedLoyaltycard.
		
- (void) getissuedLoyaltycardHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
	//NSLog(@"getissuedLoyaltycard returned the value: %@", result);
			
}
	

// Handle the response from getloyaltyCardNumber.
		
- (void) getloyaltyCardNumberHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
	//NSLog(@"getloyaltyCardNumber returned the value: %@", result);
			
}
	

// Handle the response from supplyLoyaltyCard.
		
- (void) supplyLoyaltyCardHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
	//NSLog(@"supplyLoyaltyCard returned the value: %@", result);
			
}
	

@end
		