/*
	SDZVouchercouponServiceExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "SDZVouchercouponServiceExample.h"
#import "SDZVouchercouponService.h"

@implementation SDZVouchercouponServiceExample

- (void)run {
	// Create the service
	SDZVouchercouponService* service = [SDZVouchercouponService service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

	// Returns NSString*. 
	[service getCouponDetails:self action:@selector(fv:) voucherCouponCode: @""];

	// Returns NSString*. 
	[service getCouponDetailsBySKU:self action:@selector(getCouponDetailsBySKUHandler:) skuID: @"" voucherCouponType: @""];

	// Returns NSString*. 
	[service getCurrentVouchercouponDetails:self action:@selector(getCurrentVouchercouponDetailsHandler:)];

	// Returns NSString*. 
	[service getVoucherDetails:self action:@selector(getVoucherDetailsHandler:) voucherCouponCode: @""];
}

	

// Handle the response from getCouponDetails.
		
- (void) getCouponDetailsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
	//NSLog(@"getCouponDetails returned the value: %@", result);
			
}
	

// Handle the response from getCouponDetailsBySKU.
		
- (void) getCouponDetailsBySKUHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
	//NSLog(@"getCouponDetailsBySKU returned the value: %@", result);
			
}
	

// Handle the response from getCurrentVouchercouponDetails.
		
- (void) getCurrentVouchercouponDetailsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
	//NSLog(@"getCurrentVouchercouponDetails returned the value: %@", result);
			
}
	

// Handle the response from getVoucherDetails.
		
- (void) getVoucherDetailsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
	//NSLog(@"getVoucherDetails returned the value: %@", result);
			
}
	

@end
		