/*
	SDZDealServiceExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "SDZDealServiceExample.h"
#import "SDZDealService.h"

@implementation SDZDealServiceExample

- (void)run {
	// Create the service
	SDZDealService* service = [SDZDealService service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

	// Returns NSString*. 
	[service getCurrentDealDetails:self action:@selector(getCurrentDealDetailsHandler:)];

	// Returns NSString*. 
	[service getDealDetails:self action:@selector(getDealDetailsHandler:) dealType: @"" pageNumber: @""];

	// Returns NSString*. 
	[service getDealDetailsBySKU:self action:@selector(getDealDetailsBySKUHandler:) skuID: @"" dealType: @""];
}

	

// Handle the response from getCurrentDealDetails.
		
- (void) getCurrentDealDetailsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		//NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		//NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
			
}
	

// Handle the response from getDealDetails.
		
- (void) getDealDetailsHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		//NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		//NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
			
}
	

// Handle the response from getDealDetailsBySKU.
		
- (void) getDealDetailsBySKUHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		//NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		//NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
			
}
	

@end
		