/*
	SDZLoginServiceExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "SDZLoginServiceExample.h"
#import "SDZLoginService.h"

@implementation SDZLoginServiceExample

- (void)run {
	// Create the service
	SDZLoginService* service = [SDZLoginService service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

	// Returns NSString*. 
	[service authenticateUser:self action:@selector(authenticateUserHandler:) userID: @"" password: @"" imei: @""];

	// Returns BOOL. 
	[service cancelMember:self action:@selector(cancelMemberHandler:) userID: @""];

	// Returns NSString*. 
	[service createMember:self action:@selector(createMemberHandler:) userID: @"" emailId: @"" password: @"" firstName: @"" lastName: @"" imei: @"" country: @""];

	// Returns BOOL. 
	[service forgetPassword:self action:@selector(forgetPasswordHandler:) emailId: @""];

	// Returns BOOL. 
	[service updateMemberDetails:self action:@selector(updateMemberDetailsHandler:) userID: @"" password: @"" imei: @""];
}

	

// Handle the response from authenticateUser.
		
- (void) authenticateUserHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
	//NSLog(@"authenticateUser returned the value: %@", result);
			
}
	

// Handle the response from cancelMember.
		
- (void) cancelMemberHandler: (BOOL) value {
			

	// Do something with the BOOL result
			
}
	

// Handle the response from createMember.
		
- (void) createMemberHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		//NSString* result = (NSString*)value;
	//NSLog(@"createMember returned the value: %@", result);
			
}
	

// Handle the response from forgetPassword.
		
- (void) forgetPasswordHandler: (BOOL) value {
			

	// Do something with the BOOL result
			
}
	

// Handle the response from updateMemberDetails.
		
- (void) updateMemberDetailsHandler: (BOOL) value {
			
	// Do something with the BOOL result
			
}
	

@end
		